In [ ]:
### Video Link - https://youtu.be/vrDPtxnSWos 

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [5]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [7]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [9]:
a[2]

3

In [11]:
a[3] = 13

In [13]:
a

array([ 1,  2,  3, 13,  5,  6])

In [17]:
b = a[:2]

In [15]:
b

array([1, 2])

In [19]:
b[1]

2

In [21]:
a[3:]

array([13,  5,  6])

In [23]:
a[4:]

array([5, 6])

In [31]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
a.ndim

2

In [37]:
a = np.array(23)
print('No of Dimensions - ', a.ndim)
print('Shape - ', a.shape)
print('Len of Shape - ', len(a.shape))
print('Size - ', a.size)

No of Dimensions -  0
Shape -  ()
Len of Shape -  0
Size -  1


In [39]:
a = np.array([1, 2])
print('No of Dimensions - ', a.ndim)
print('Shape - ', a.shape)
print('Len of Shape - ', len(a.shape))
print('Size - ', a.size)

No of Dimensions -  1
Shape -  (2,)
Len of Shape -  1
Size -  2


In [41]:
a = np.array([1, 2, 3])
print('No of Dimensions - ', a.ndim)
print('Shape - ', a.shape)
print('Len of Shape - ', len(a.shape))
print('Size - ', a.size)

No of Dimensions -  1
Shape -  (3,)
Len of Shape -  1
Size -  3


In [43]:
a = np.array([[1, 2], 
              [1, 2]])
print('No of Dimensions - ', a.ndim)
print('Shape - ', a.shape)
print('Len of Shape - ', len(a.shape))
print('Size - ', a.size)

No of Dimensions -  2
Shape -  (2, 2)
Len of Shape -  2
Size -  4


In [53]:
a = np.array([[1, 2, 6, 7], 
              [1, 2, 6, 7]])
print('No of Dimensions - ', a.ndim)
print('Shape - ', a.shape)
print('Len of Shape - ', len(a.shape))
print('Size - ', a.size)

No of Dimensions -  2
Shape -  (2, 4)
Len of Shape -  2
Size -  8


In [55]:
a = np.array([
                [[1, 2, 6], 
                [1, 2, 6]],
            
                [[1, 2, 5], 
                [1, 2, 4]]
])
print('No of Dimensions - ', a.ndim)
print('Shape - ', a.shape)
print('Len of Shape - ', len(a.shape))
print('Size - ', a.size)

No of Dimensions -  3
Shape -  (2, 2, 3)
Len of Shape -  3
Size -  12


In [57]:
a = np.array([[
                [[1, 2, 6], 
                [1, 2, 6]],
            
                [[1, 2, 5], 
                [1, 2, 4]]
            ],
             [
                [[1, 2, 6], 
                [1, 2, 6]],
            
                [[1, 2, 5], 
                [1, 2, 4]]
            ]]
            )
print('No of Dimensions - ', a.ndim)
print('Shape - ', a.shape)
print('Len of Shape - ', len(a.shape))
print('Size - ', a.size)

No of Dimensions -  4
Shape -  (2, 2, 2, 3)
Len of Shape -  4
Size -  24


In [59]:
a.dtype

dtype('int64')

In [67]:
np.zeros(2)

array([0., 0.])

In [71]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [75]:
np.zeros((2,3,7, 4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0.

In [77]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [79]:
np.ones((6, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [81]:
np.empty(3)

array([4.9e-324, 9.9e-324, 1.5e-323])

In [83]:
np.empty((3, 8))

array([[    nan,     nan, 0.e+000,     nan, 5.e-324,     nan, 1.e-323,
            nan],
       [5.e-324, 0.e+000, 1.e-323, 5.e-324, 5.e-324, 1.e-323, 0.e+000,
        5.e-324],
       [    nan, 1.e-323,     nan, 5.e-324,     nan, 0.e+000,     nan,
            nan]])

In [89]:
np.arange(2, 10, 0.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ,
       8.5, 9. , 9.5])

In [95]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [97]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [99]:
x = np.zeros(2, dtype=np.int64)
x

array([0, 0])

In [101]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [103]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [105]:
arr = np.array([30, 10, 20])
np.argsort(arr)

array([1, 2, 0])

In [113]:
arr = np.array([90, 98, 23, 89, 12, 43, 76])
np.partition(arr, 5)

array([12, 76, 23, 43, 89, 90, 98])

In [117]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [127]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
z = np.array([[8,9]])
np.concatenate((x, y, z), axis=0)

(2, 2)
(1, 2)


array([[1, 2],
       [3, 4],
       [5, 6],
       [8, 9]])

In [177]:
a = np.arange(2, 10, 2)

In [179]:
a

array([2, 4, 6, 8])

In [185]:
a.reshape(2,2)

array([[2, 4],
       [6, 8]])

In [187]:
a = np.arange(1, 7)

In [189]:
a

array([1, 2, 3, 4, 5, 6])

In [191]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [193]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [207]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [209]:
np.reshape(arr, (3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [205]:
np.reshape(arr, (2, 3), order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [211]:
arr = np.arange(6)
np.reshape(arr, (3,2))
np.reshape(arr, (2,3), order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [227]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [229]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [231]:
a.ndim

1

In [233]:
a2.ndim

2

In [235]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [237]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [239]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [241]:
arr = np.array([12, 89, 45])

In [243]:
arr[1:]

array([89, 45])

In [245]:
arr[2:]

array([45])

In [247]:
arr[2]

45

In [249]:
arr[3:]

array([], dtype=int64)

In [251]:
arr[-2]

89

In [253]:
arr[-2:]

array([89, 45])

In [257]:
arr[:-1]

array([12, 89])

In [259]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [261]:
a < 6

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [263]:
a[a<6]

array([1, 2, 3, 4, 5])

In [265]:
a = np.array([[13 , 62, 3, 42], [75, 6, 7, 84], [93, 10, 2, 12]])

In [267]:
a<7

array([[False, False,  True, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [275]:
a[(a<7) | (a>75)]

array([ 3,  6, 84, 93,  2])

In [277]:
np.nonzero((a<7) | (a>75))

(array([0, 1, 1, 2, 2]), array([2, 1, 3, 0, 2]))

In [283]:
a1 = np.array([[1, 1, 3],
               [2, 2, 4]])

a2 = np.array([[3, 3, 6],
               [4, 4, 7]])

In [285]:
np.vstack((a1, a2))

array([[1, 1, 3],
       [2, 2, 4],
       [3, 3, 6],
       [4, 4, 7]])

In [287]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [289]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [291]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [295]:
np.hsplit(x, (3, 4, 7, 8))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7],
        [17, 18, 19]]),
 array([[ 8],
        [20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [297]:
arr = np.arange(6)

In [299]:
b = arr

In [301]:
print(arr)
print(b)

[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [303]:
b[2] = 10

In [305]:
print(arr)
print(b)

[ 0  1 10  3  4  5]
[ 0  1 10  3  4  5]


In [307]:
arr = np.arange(6)

In [309]:
arr

array([0, 1, 2, 3, 4, 5])

In [311]:
b = arr[2:4]

In [313]:
b

array([2, 3])

In [315]:
b[1] = 20

In [317]:
arr

array([ 0,  1,  2, 20,  4,  5])

In [319]:
arr = np.arange(6)
b = arr.copy()

In [321]:
b[2] = 20

In [323]:
print(arr)
print(b)

[0 1 2 3 4 5]
[ 0  1 20  3  4  5]


In [329]:
a = np.arange(2, 10)
b = np.arange(5, 15)
print(a)
print(b)

[2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12]


In [331]:
a + b

array([ 7,  9, 11, 13, 15, 17, 19, 21])

In [333]:
a - b

array([-3, -3, -3, -3, -3, -3, -3, -3])

In [335]:
a * b

array([ 10,  18,  28,  40,  54,  70,  88, 108])

In [337]:
a / b

array([0.4       , 0.5       , 0.57142857, 0.625     , 0.66666667,
       0.7       , 0.72727273, 0.75      ])

In [339]:
a.sum()

44

In [341]:
a = np.arange(1, 10)
b = np.arange(1, 10)
print(a)
print(b)
print(a.sum())

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
45


In [349]:
b = a.reshape(3,3)

In [351]:
b.sum(axis = 0)

array([12, 15, 18])

In [353]:
a = np.arange(1, 10).reshape(3,3)
print(a)
a.sum(axis = 0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [355]:
a.sum(axis = 1)

array([ 6, 15, 24])

In [357]:
a.max()

9

In [359]:
a.min()

1

In [361]:
a.max(axis = 0)

array([7, 8, 9])

In [363]:
a.min(axis = 1)

array([1, 4, 7])

In [367]:
a.prod(axis = 1)

array([  6, 120, 504])

In [369]:
a.mean(axis = 1)

array([2., 5., 8.])

In [375]:
a.std()

2.581988897471611

In [377]:
np.random.randint(2, 9, (3, 2))

array([[8, 4],
       [7, 4],
       [5, 6]])

In [393]:
rng = np.random.default_rng()
rng.integers(5, size=(2, 4)) 

array([[1, 3, 1, 2],
       [1, 4, 4, 4]])

In [397]:
arr = rng.integers(2, 9, (3, 2)) 

In [399]:
arr

array([[3, 6],
       [8, 6],
       [5, 5]])

In [401]:
arr.T

array([[3, 8, 5],
       [6, 6, 5]])

In [403]:
arr.transpose()

array([[3, 8, 5],
       [6, 6, 5]])

In [405]:
arr

array([[3, 6],
       [8, 6],
       [5, 5]])

In [407]:
arr.transpose()

array([[3, 8, 5],
       [6, 6, 5]])

In [409]:
arr

array([[3, 6],
       [8, 6],
       [5, 5]])

In [411]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [413]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [415]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [417]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [419]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [421]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [423]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [425]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array
print(a1)  # New array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [427]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array
print(a2)  # New array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]


In [429]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.

